name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy to VM
      env:
        HOST: ${{ secrets.VM_HOST }}
        USER: ${{ secrets.VM_USER }}
        PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > C:/Users/dnshm/Desktop/Projects/far-alpha/Dinesh-challenge-vm_key.pem
        chmod 600 C:/Users/dnshm/Desktop/Projects/far-alpha/Dinesh-challenge-vm_key.pem
        ssh -i C:/Users/dnshm/Desktop/Projects/far-alpha/Dinesh-challenge-vm_key.pem -o StrictHostKeyChecking=no $USER@$HOST "pm2 stop all || true && pm2 start index.js --name far-alpha"
        rm C:/Users/dnshm/Desktop/Projects/far-alpha/Dinesh-challenge-vm_key.pem